name: (Manual) Build, test and release snap

on:
  workflow_dispatch:
    # this trigger uses existing version for release

jobs:
  prereqs:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps._id.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        id: _id
        run: |
          tag="$(awk -F: '/^version:/ {print $2}' snap/snapcraft.yaml | tr -d '[:space:]')"
          echo "tag: $tag"
          echo "version=$tag" >> $GITHUB_OUTPUT

  build-and-test:
    needs: [ prereqs ]
    uses: RocketChat/server-snap/.github/workflows/test.yml@develop
    with:
      tag: ${{ needs.prereqs.outputs.version }}
    secrets:
      snapcraft-credential: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}

  release:
    needs:
      - build-and-test
    uses: RocketChat/server-snap/.github/workflows/release.yml@develop
    with:
      snap: ${{ needs.build-and-test.outputs.snap-basename }}
      snap-track: ${{ needs.build-and-test.outputs.snap-track }}
      commit: ${{ needs.build-and-test.outputs.commit }}
      tag: ${{ inputs.tag }}
    secrets:
      snapcraft-credential: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
      github-token: ${{ secrets.GITHUB_TOKEN }}

